
(deftemplate drug-item
	(slot drug-name)
	(slot action)
	(slot side-effect)
)

(deftemplate user-input
   (slot first-drug)
   (slot second-drug)
)

(deftemplate action-exception
    (slot action1)
    (slot action2)
)

(deftemplate add-action
	(slot action1)
	(slot action2)
)

(deftemplate add-side-effect
    (slot action1)
    (slot action2)
    (slot new-side-effect)
)                                

(deffacts initial-facts
	(drug-item (drug-name "Pyrantel-Pamoate") (action "Spastic-Paralysis") (side-effect "Activates nicotinic cholinergic receptors"))
	(drug-item (drug-name "Piperazine") (action "Flaccid-Paralysis") (side-effect "Prevents acetylcholine actions"))
	(drug-item (drug-name "Phenoxybenzamine") (action "Irreversibly blocks Alpha-1 and Alpha-2,  indirect baroreflex activation") (side-effect "Lowers blood pressure (BP) and heart rate (HR) rises due to baroreflex activation"))
	(drug-item (drug-name "Phentolamine") (action "Reversibly blocks Alpha-1 and Alpha-2") (side-effect "Blocks Alpha--mediated vasoconstriction, lowers BP, increases HR (baroreflex)"))
	(drug-item (drug-name "Prazosin") (action "Block Alpha-1, but not Alpha-2") (side-effect "Lower BP"))
	(drug-item (drug-name "Tamsulosin") (action "Tamsulosin is slightly selective for Alpha-1A") (side-effect "Alpha-1A Blockade may relax prostatic smooth muscles more than vascular smooth muscle"))
	(drug-item (drug-name "Yohimbine") (action "None") (side-effect "Raises BP and HR"))
	(drug-item (drug-name "Labetalol") (action "Alpha-adrenoceptor–blocking action") (side-effect "Lowers BP with limited HR increase"))
	(drug-item (drug-name "Propranolol") (action "Block Beta-1 and Beta-2") (side-effect "Lower HR and BP and reduce renin"))
	(drug-item (drug-name "Metoprolol") (action "Block Beta-1 > Beta-2") (side-effect "None"))
	(drug-item (drug-name "Pindolol") (action "Beta-1, Beta-2, with intrinsic sympathomimetic (partial agonist) effect") (side-effect "Lowers BP and modestly lower HR"))
	(drug-item (drug-name "Esmolol") (action "Beta-1 > Beta-2") (side-effect "Very brief cardiac Beta- blockade"))
	(drug-item (drug-name "Metyrosine") (action "Blocks tyrosine hydroxylase and reduces synthesis of dopamine, norepinephrine, and epinephrine") (side-effect "Lowers BP and in central nervous system may elicit extrapyramidal effects (due to low dopamine)"))
	(drug-item (drug-name "Albuterol") (action "Selective Beta-2 agonist") (side-effect "Prompt, efficacious bronchodilation"))
	(drug-item (drug-name "Epinephrine") (action "Nonselective Alpha- and Beta- agonist") (side-effect "Bronchodilation plus all other sympathomimetic effects on cardiovascular and other organ systems"))
	(drug-item (drug-name "Isoproterenol") (action "Beta-1 and Beta-2 agonist") (side-effect "Bronchodilation plus powerful cardiovascular effects"))
	(drug-item (drug-name "Fluticasone") (action "Alters gene expression") (side-effect "Reduces mediators of inflammation and powerful prophylaxis of exacerbations"))
	(drug-item (drug-name "Prednisone") (action "Like fluticasone") (side-effect "Like fluticasone"))
	(drug-item (drug-name "Cromolyn, Nedocromil") (action "Alter function of delayed chloride channels") (side-effect "Prevents acute bronchospasm"))
	(drug-item (drug-name "Theophylline") (action "Uncertain, phosphodiesterase, adenosine receptor antagonist inhibition") (side-effect "Bronchodilation, cardiac stimulation, increased skeletal muscle strength (diaphragm)"))
	(drug-item (drug-name "Montelukast, Zafirlukas") (action "Block leukotriene D4 receptors") (side-effect "Block airway response to exercise and antigen challenge"))
	(drug-item (drug-name "Omalizumab") (action "Humanized IgE antibody reduces circulating IgE") (side-effect "Reduces frequency of asthma exacerbations"))
	(drug-item (drug-name "Naloxone") (action "Nonselective antagonist of opioid receptors") (side-effect "Reverses the acute effects of opioids; can precipitate severe abstinence syndrome"))
	(drug-item (drug-name "Naltrexone") (action "Antagonist of opioid receptors") (side-effect "Blocks effects of illicit opioids"))
	(drug-item (drug-name "Methadone") (action "Slow-acting agonist of Mu--opioid receptor") (side-effect "Acute effects similar to morphine (see text)"))
	(drug-item (drug-name "Buprenorphine") (action "Partial agonist at Mu--opioid receptors") (side-effect "Attenuates acute effects of morphine"))
	(drug-item (drug-name "Varenicline") (action "Partial agonist of nicotinic acetylcholine receptor of the Alpha-4Beta-2-type") (side-effect "Occludes �rewarding� effects of smoking and heightened awareness of colors"))
	(drug-item (drug-name "Oxazepam") (action "Positive modulators of the GABAA receptors, increase frequency of channel opening") (side-effect "Enhances GABAergic synaptic transmission; attenuates withdrawal symptoms (tremor, hallucinations, anxiety) in alcoholics and prevents withdrawal seizures"))
	(drug-item (drug-name "Acamprosate") (action "Antagonist of NMDA glutamate receptors") (side-effect "May interfere with forms of synaptic plasticity that depend on NMDA receptors"))
	(drug-item (drug-name "Rimonabant") (action "CB1 receptor inverse agonist") (side-effect "Decreases neurotransmitter release at GABAergic and glutamatergic synapses"))
	(drug-item (drug-name "Atorvastatin") (action "Inhibit HMG-CoA reductase") (side-effect "Reduce cholesterol synthesis and up-regulate low-density lipoprotein (LDL) receptors on hepatocytes and modest reduction in triglycerides"))
	(drug-item (drug-name "Fenofibrate") (action "Peroxisome proliferator-activated receptor-alpha (PPAR-Alpha-) agonists") (side-effect "None"))
	(drug-item (drug-name "Colestipol") (action "None") (side-effect "Decreases LDL"))
	(drug-item (drug-name "Ezetimibe") (action "Blocks sterol transporter NPC1L1 in intestine brush border") (side-effect "Inhibits reabsorption of cholesterol excreted in bile and decreases LDL and phytosterols"))
	(drug-item (drug-name "Niacin") (action "Decreases catabolism of apo AI and reduces VLDL secretion from liver") (side-effect "Increases HDL and decreases lipoprotein(a) [Lp(a)], LDL, and triglycerides"))
	(drug-item (drug-name "Cholecalciferol") (action "Regulate gene transcription via the vitamin D receptor") (side-effect "None"))
	(drug-item (drug-name "Alendronate") (action "Suppress the activity of osteoclasts in part via inhibition of farnesyl pyrophosphate synthesis") (side-effect "Inhibit bone resorption and secondarily bone formation"))
	(drug-item (drug-name "Teriparatide") (action "These hormones act via their cognate G proteincoupled receptors their cognate G proteincoupled receptors") (side-effect "Teriparatide stimulates bone turnover and calcitonin suppresses bone resorption"))
	(drug-item (drug-name "Raloxifene") (action "Interacts selectively with estrogen receptors") (side-effect "Inhibits bone resorption without stimulating breast or endometrial hyperplasia"))
	(drug-item (drug-name "Denosumab") (action "Monoclonal antibody and binds to RANKL and prevents it from stimulating osteoclast differentiation and function") (side-effect "Blocks bone resorption"))
	(drug-item (drug-name "Cinacalcet") (action "Activates the calciumsensing receptor") (side-effect "Inhibits PTH secretion"))
	(drug-item (drug-name "Calcium") (action "Multiple physiologic actions through regulation of multiple enzymatic pathways") (side-effect "Strontium suppresses bone resorption and increases bone formation and calcium and phosphate required for bone mineralization"))
	(drug-item (drug-name "Ganirelix") (action "Blocks GnRH receptors") (side-effect "Reduces endogenous production of LH and FSH"))
	(drug-item (drug-name "Haloperidol") (action "Block central D2 receptors") (side-effect "Reduce vocal and motor tic frequency, severity"))
	(action-exception (action1 "Irreversibly blocks Alpha-1 and Alpha-2,  indirect baroreflex activation") (action2 "Reversibly blocks Alpha-1 and Alpha-2"))
	(action-exception (action1 "Activates oxytocin receptors") (action2 "Blocks oxytocin receptors"))
	(action-exception (action1 "Recombinant form of human GH acts through GH receptors to increase production of IGF-") (action2 "Blocks GH receptors"))
	(action-exception (action1 "Flaccid-Paralysis") (action2 "Spastic-Paralysis"))
	(action-exception (action1 "Competitively blocks Beta-1 receptors") (action2 "Beta-1 and Beta-2 agonist"))
	(action-exception (action1 "Antagonist of vasopressin V1a and V2 receptors") (action2 "Relatively selective vasopressin V2 receptor agonist"))
	(add-side-effect (action1 "Alpha-adrenoceptor–blocking action") (action2 "Block central D2 receptors") (new-side-effect "Addiction"))
	(add-side-effect (action1 "quinidine-like") (action2 "produce pharmacodynamic") (new-side-effect "Addiction"))
	(add-side-effect (action1 "block the gamma-carboxylation") (action2 "augment the hypoprothrombinemia") (new-side-effect "inhibit platelet function and may induce peptic ulcer disease"))
	(add-side-effect (action1 "Blockade of sodium channels") (action2 "produce pharmacodynamic") (new-side-effect "torsades de pointes"))
)